# Page settings

baseURL = "https://bipeens.github.io/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"



[params]
    author = "Bipeen Sawant"
    description = "Lead DevOps Engineer Resume"


    primaryColor = "#54B689"
    textPrimaryColor = "#292929"




[params.profile]
    enable = true
    name = "Bipeen Sawant"
    tagline = "Lead DevOps Engineer"
    avatar = "Bipin.png"




[params.contact]
    enable = true
    location = "Pune, India"

    [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+91-xxxxxxxxxx"
    [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "bxxxxxxx8@gmail.com"
    [[params.contact.list]]
        icon = "fas fa-globe"
        url = "site/"
        text = "http://bipeens.github.io/"







[params.skills]
    enable = true

    [[params.skills.list]]
        title = "Technical"
    [[params.skills.list.items]]
        details = "Kubernetes/Mesos"
    [[params.skills.list.items]]
        details = "AWS"
    [[params.skills.list.items]]
        details = "Bash/Python/Groovy"
    [[params.skills.list.items]]
        details = "Docker/Helm/Packer"
    [[params.skills.list.items]]
        details = "Terraform/Vagrant/Ansible"
    [[params.skills.list.items]]
        details = "Linux/Centos/Ubuntu"
    [[params.skills.list.items]]
        details = "Logging stack (ELK)"
    [[params.skills.list.items]]
        details = "Monitoring Stack (Grafana/Prometheus/TICK)"
    [[params.skills.list.items]]
        details = "Postgresql/DynamoDB"
    [[params.skills.list.items]]
        details = "Building enterprise class, highly available CI/CD gitops pipelines"
    [[params.skills.list.items]]
        details = "GitHub/Jenkins"
    [[params.skills.list]]
        title = "Professional"
    [[params.skills.list.items]]
        details = "Effective communication"
    [[params.skills.list.items]]
        details = "Team player"
    [[params.skills.list.items]]
        details = "Strong problem solver"
    [[params.skills.list.items]]
        details = "Good time management"



[params.education]
    enable = true

    [[params.education.list]]
        degree = "BE Computer"
        university = "Mumbai University"
        dates = "2005 - 2009"


[params.languages]
    enable = true

    [[params.languages.list]]
        name = "English"
        level = "Professional"
    [[params.languages.list]]
        name = "Hindi"
        level = "Native"
    [[params.languages.list]]
        name = "Marathi"
        level = "Native"








[params.interests]
    enable = true

    [[params.interests.list]]
        name = "Badminton"
    [[params.interests.list]]
        name = "Travelling"
    [[params.interests.list]]
        name = "Table Tennis"



[params.summary]
    enable = true
    text = "Lead Devops Engineer with 12+ years of experience finding solutions and determining customer satisfaction. Overall experience compromises Devops Engineering, Building IAAS, Automation, Deployment, Linux Administration, Extensive experience in SCM."





[params.experience]
    enable = true

    [[params.experience.list]]
        title = "Lead DevOps Engineer"
        dates = "January 2021 - Present"
        company = "Cisco Systems Pvt Ltd"
        details = "Built a platform on AWS EKS providing infrastructure services including Logging, Monitoring, Distribute Tracing, Datastores, Secret Management, Security with HA/DR capabilities, ServiceMesh, Messaging. "
        [[params.experience.list.items]]
            details = "Built an enterprise class, highly available CI/CD pipelines from code"
	    [[params.experience.list.items]]
            details = " Managing lifecycle for multi tenant product deployments."
        [[params.experience.list.items]]
            details = "Working on infosec annd CSDL activities for Kubernetes Hardening"
	    [[params.experience.list.items]]
            details = "Lead a team of 6 Full time Devops Engineers and 5 Contractors."
        [[params.experience.list.items]]
            details = "Cloud cost optimization."

    [[params.experience.list]]
        title = "Lead DevOps Engineer"
        dates = "July 2015 - Jan 2021"
        company = "GSLab Pvt Ltd"
        details = "Building a platform to solve common challenges in IAAS where devices and applications are highly distributed. It includes designing, implementing and automating infrastructure along with monitoring, logging, alerting and operations part of the system in place."
        [[params.experience.list.items]]
            details = "Infrastructure Automation"
	    [[params.experience.list.items]]
            details = "Containerization"
        [[params.experience.list.items]]
            details = "Centralized Logging"
        [[params.experience.list.items]]
            details = "Monitoring and alerting"
	    [[params.experience.list.items]]
            details = "Continuous Integration and Continuous Delivery"
        [[params.experience.list.items]]
            details = "Worked on migration of Mesos architecture to Kubernetes"
	    [[params.experience.list.items]]
            details = "Incorporating devops culture in the team"

    [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "April 2010 - July 2015"
        company = "Cybage Software Pvt Ltd"
        details = "Working on a product, a Java/J2EE web application, which provides comprehensive enterprise eCommerce solutions built on the DigitalRiver | globalCommerce™ platform."
        [[params.experience.list.items]]
            details = "Implementing Messaging system using Apache Kafka"
	    [[params.experience.list.items]]
            details = "Providing approaches and solutions to new feature enhancement tasks. "
        [[params.experience.list.items]]
            details = "Implemented Conformance testing framework to test JDO layer architecture"
	    [[params.experience.list.items]]
            details = "Logging, Monitoring and alerting"
	    [[params.experience.list.items]]
            details = "Implemented new integrations using Oauth 2.0 and OpenID"
        [[params.experience.list.items]]
            details = "Working as a QL (Quality Leader)"



    [params.projects]
        enable = true

        [[params.projects.list]]
            title = "IOTOD"
            meta = "Jan 2021 - Present"
            tagline = "A platform on AWS EKS providing infrastructure services including Logging, Monitoring, Distribute Tracing, Datastores, Secret Management, Security with HA/DR capabilities, ServiceMesh, Messaging."
            technologies = "Technologies: AWS, Kubernetes, ELK Stack, Prometheus Stack, TICK Stack, Terraform, Helm, Istio, Influxdb, External-dns, RabbitMQ, Postgres"
            [[params.projects.list.items]]
                details = "Built a IAAS platform on AWS using EKS from scratch using terraform."
            [[params.projects.list.items]]
                details = "Worked on various AWS services in the platform"
            [[params.projects.list.items]]
                details = "Worked on building AMIs using packer for kubernetes/Mesos using Centos as base images"
            [[params.projects.list.items]]
                details = "Designed and Created CI/CD pipelie using Gitops for the architecture"
            [[params.projects.list.items]]
                details = "Created a Disaster Recovery architecture and pipeline which is carried every quarter"
            [[params.projects.list.items]]
                details = "Managing Tenants with their onboarding over the platform"
            [[params.projects.list.items]]
                details = "Designed and Implemented Service Mesh ito the architecture"
            [[params.projects.list.items]]
                details = "Designed and Implemented Vault for Secfet Management"
            [[params.projects.list.items]]
                details = "Implemented autoscaling feature for nodes and services"
            [[params.projects.list.items]]
                details = "Designed and Implemented Certificate Management in the platform"
            [[params.projects.list.items]]
                details = "Implemented AWS Shield for DDos attack and Network Firewall to filter traffic"
            [[params.projects.list.items]]
                details = "Design, review and help the team to work in the agile environment"
            [[params.projects.list.items]]
                details = "Worked on various security tools like CIS Benchmark, Falco, Qualys, SecureAppCN, Corona"
            [[params.projects.list.items]]
                details = "Created CI/CD pipelie using Gitops for the architecture"
            [[params.projects.list.items]]
                details = "Manage SRE team with their daily activities"

        [[params.projects.list]]
            title = "IOT Software Platform"
            meta = "August 2015 - January 2021"
            tagline = "It is a platform to solve common challenges in IAAS where devices and applications are highly distributed. This, helps you put compute power where you need it. "
            technologies = "Technologies: Docker, Kubernetes, Elasticsearch, Logstash, Kibana, Grafana, Prometheus, TICK Stack, Helm, Terraform, Ansible, AWS, Consul, HaProxy"
            [[params.projects.list.items]]
                details = "Working on complex enterprise application in Cloud Infrastructure domain mostly on AWS"
            [[params.projects.list.items]]
                details = "Experience in building fairly complex micro-services based platform using Docker, Kubernetes, Terraform, Ansible, Mesos, Marathon, Zookeeper, Consul DNS discovery, HAProxy, Chronos, Artifactory."
            [[params.projects.list.items]]
                details = "Created own gitops pipeline for CICD automation for helmcharts deployment"
            [[params.projects.list.items]]
                details = "Created an automated CICD pipeline for terraform and helmchart deployment across the build environments"
            [[params.projects.list.items]]
                details = "Worked on migration of Mesos architecture to kubernetes"
            [[params.projects.list.items]]
                details = "Worked on infrastructure automation using tools like Terraform, Ansible, Packer, Docker, Vagrant"
            [[params.projects.list.items]]
                details = "Development and implementation of various AWS public cloud offerings like EC2, RDS, S3, Cloudwatch, Route53, VPC, EBS, EFS etc."
            [[params.projects.list.items]]
                details = "Implemented AWS Lambda jobs for disaster Recovery of the cluster."
            [[params.projects.list.items]]
                details = "Developing docker images for infra components like mesos, consul, zookeeper, etc."
            [[params.projects.list.items]]
                details = "Experience with monitoring stack like TIGK (Telegraf Influxdb Grafana Kapacitor)."
            [[params.projects.list.items]]
                details = "Developed and implemented Logging system using ELK(Elasticsearch Logstash Kibana) ad EFK(Elasticsearch Fluentbit Kibana)"
            [[params.projects.list.items]]
                details = "Experience working in Linux environment – CentOS, Ubuntu."
            [[params.projects.list.items]]
                details = "Extensively worked on Agile (SCRUM) development model."
            [[params.projects.list.items]]
                details = "Experience in shell and python scripting."
            [[params.projects.list.items]]
                details = "Worked with aws and openstack clients like awscli, python-openstackclient. "
            [[params.projects.list.items]]
                details = "Worked on applying infosec and CSDL activities for kubernetes hardening."
            [[params.projects.list.items]]
                details = "Sound knowledge of container runtime like Docker (runc, containerd), container orchestrator like Mesos, kubernetes."
            [[params.projects.list.items]]
                details = "Experience with Jira ticketing system."
            [[params.projects.list.items]]
                details = "Experience with Confluence, a collaboration software."
            [[params.projects.list.items]]
                details = "Linux and container debugging skills."
            [[params.projects.list.items]]
                details = "Open source contribution in Flocker, Mesos."
            [[params.projects.list.items]]
                details = "Working as team lead to mentor new resources."

        [[params.projects.list]]
            title = "GlobalCommerce"
            meta = "April 2010 - July 2015"
            tagline = "GlobalCommerce is a product, a Java/J2EE web application, which provides comprehensive enterprise eCommerce solutions built on the DigitalRiver | globalCommerce™ platform"
            technologies = "Technologies: Java, Spring, JDO, JMS, Kafka"
            [[params.projects.list.items]]
                details = "Working on implementing Messaging system using Apache Kafka"
            [[params.projects.list.items]]
                details = "Implemented Conformance testing framework to test JDO layer architecture and Messaging layer"
            [[params.projects.list.items]]
                details = "Interacting with client about issues and defects"
            [[params.projects.list.items]]
                details = "Developing docker images for infra components"
            [[params.projects.list.items]]
                details = "Providing approaches and solutions to new feature enhancement tasks"
            [[params.projects.list.items]]
                details = "Working as a QL (Quality Leader)"
            [[params.projects.list.items]]
                details = "Experience working in Linux environment – CentOS, Ubuntu"
            [[params.projects.list.items]]
                details = "Extensively worked on Agile (SCRUM) development model"
            [[params.projects.list.items]]
                details = "Experience in shell and python scripting"
            [[params.projects.list.items]]
                details = "Implemented new integrations using Oauth2.0 and OpenID" 
            [[params.projects.list.items]]
                details = "Writing JMock test cases for whole API testing"
            [[params.projects.list.items]]
                details = "Writing FIT test cases for API testing"
            [[params.projects.list.items]]
                details = "Creating UML diagrams for enhancement design"
            [[params.projects.list.items]]
                details = "Experience with Jira ticketing system"
            [[params.projects.list.items]]
                details = "Experience with Confluence, a collaboration software"
            [[params.projects.list.items]]
                details = "Linux and container debugging skills"



    [params.information]
        enable = true

        [[params.information.list]]
            title = "Certifications"
        [[params.information.list.items]]
            details = "Certified Kubernetes Administrator (CKA)"
        [[params.information.list.items]]
            details = "Certified Kubernetes Application Developer (CKAD)"

        [[params.information.list]]
            title = "Technology Stack"
        [[params.information.list.items]]
            details = "CI/CD - Jenkins"
        [[params.information.list.items]]
            details = "Virtualization - AWS, Azure, Openstack, IBM Bluemix"
        [[params.information.list.items]]
            details = "Infrastructure Automation - Terraform, Vagrant, Packer, Rancher"
        [[params.information.list.items]]
            details = "Service Discovery - Consul"
        [[params.information.list.items]]
            details = "Load Balancer - HAProxy, Nginx, Traefik, AWS ELB, Azure LB"
        [[params.information.list.items]]
            details = "Configuration Management - Ansible"
        [[params.information.list.items]]
            details = "Container Runtime - Docker"
        [[params.information.list.items]]
            details = "Container Orchestrator - Mesos, Kubernetes"
        [[params.information.list.items]]
            details = "Monitoring - TIGK [Telegraf, InfluxDB, Grafana, Kapacitor], Percona, Prometheus, Alertmanager"
        [[params.information.list.items]]
            details = "API Gateway - Istio, nginx-ingress"
        [[params.information.list.items]]
            details = "Container Security - Twistlock, coreos clair, docker-bench security"
        [[params.information.list.items]]
            details = "Scripting - Shell, Python"
        [[params.information.list.items]]
            details = "Database - Elasticsearch, MongoDB"
        [[params.information.list.items]]
            details = "Log Collector - Fluentd, Filebeat"
        [[params.information.list.items]]
            details = "Streaming Platform - Kafka"
        [[params.information.list.items]]
            details = "Packaging Tool - Helm"
        [[params.information.list.items]]
            details = "Visualization - Kibana"
        [[params.information.list.items]]
            details = "Source Code Management - Git"
        [[params.information.list.items]]
            details = "Ticketing System - Jira"
        [[params.information.list.items]]
            details = "Collaboration Software - Confluence"
        [[params.information.list.items]]
            details = "Operations Tools - Pagerduty, Pingdom, Statuspage"
        [[params.information.list.items]]
            details = "Operating systems - Ubuntu, CentOS, Windows"

        [[params.information.list]]
            title = "Interests"
            details = "Badminton, Table Tennis,Travelling"




    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/bipeens"
        title = "bipeensawant"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/bipeen-sawant"
        title = "bipeen-sawant"
	[[params.social.list]]
        icon = "fab fa-facebook-square"
        url = "//facebook.com/bipeen.sawant"
        title = "bipin.sawant"

